version: '3.7'
services: 
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: pass
        ports: 
          - 5432:5432

    adminer:
        image: adminer:latest
        restart: always
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        ports: 
          - 8080:8080
